jakartaee/concurrency

api/.gitignore
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
=> Added .gitignore file

api/pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
=> Update plugins preventing building

api/pom.xml
Signed-off-by: Mark Wareham <mark.wareham@payara.fish>
=> Updated parent pom version

api/pom.xml
Fixed version numbers ref https://github.com/eclipse-ee4j/concurrency-api/issues/45
=> Fixed version numbers

api/pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
=> Updated spec version

api/pom.xml
Signed-off-by: Jonathan Coustick <jonathan.coustick@payara.fish>
=> Updated parent pom to 1.0.4

CONTRIBUTING.md, NOTICE.md, README.md, api/pom.xml, api/src/main/doc-files/speclicense.html, api/src/main/java/javax/enterprise/concurrent/ContextService.java, api/src/main/java/javax/enterprise/concurrent/ManageableThread.java, api/src/main/java/javax/enterprise/concurrent/ManagedExecutorService.java, api/src/main/java/javax/enterprise/concurrent/ManagedScheduledExecutorService.java, api/src/main/java/javax/enterprise/concurrent/ManagedTask.java, api/src/main/java/javax/enterprise/concurrent/ManagedThreadFactory.java, api/src/main/java/javax/enterprise/concurrent/Trigger.java, api/src/main/java/javax/enterprise/concurrent/package-info.java
=> Clean up of API for Jakarta EE 8

api/pom.xml, specification/src/main/asciidoc/license-efsl.adoc
=> Update copyright to the Eclipse Foundation

api/pom.xml
Needs to be approved to restage artifacts with the correct licenses
=> Ensure license is correctly packaged in api jar and javadocs

api/pom.xml
Merge in release branch created by Jenkins
=> Release 1.1.2

api/src/main/java/jakarta/enterprise/concurrent/ManagedTask.java, api/src/main/java/jakarta/enterprise/concurrent/SkippedException.java
=> Fix incorrect javadoc links

api/pom.xml, specification/pom.xml
=> Update parent pom to 1.0.6

api/pom.xml
Comment out the plugin until the bug is fixed in validating version numbers. This will enable us to push an RC to maven central
=> Comment out check-module goal as the plugin needs fixing

specification/src/main/asciidoc/jakarta-concurrency.adoc
=> Fix incorrect package name for javax.sql.Connection

CONTRIBUTING.md
Add required section
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> #122 Eclipse Development Process

api/src/main/java/doc-files/speclicense.html, specification/src/main/asciidoc/license-efsl.adoc
=> Updates license references

api/pom.xml, api/src/main/java/jakarta/enterprise/concurrent/AbortedException.java, api/src/main/java/jakarta/enterprise/concurrent/ContextService.java, api/src/main/java/jakarta/enterprise/concurrent/LastExecution.java, api/src/main/java/jakarta/enterprise/concurrent/ManageableThread.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorService.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutors.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorService.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedTask.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedTaskListener.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactory.java, api/src/main/java/jakarta/enterprise/concurrent/SkippedException.java, api/src/main/java/jakarta/enterprise/concurrent/Trigger.java
=> POM Clean up and update to javadoc plugin with minor corrections

tck/pom.xml, tck/src/main/java/ee/jakarta/tck/concurrent/framework/TestLogger.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/JSPSecurityServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/jspTests.jsp
Tests to ensure that context propagation works as expected as part of a JSP servlet.
=> Introduce Context Propegation JSP tests

api/pom.xml, pom.xml, tck/pom.xml
Creates a parent pom above api and tck modules so they are both built together.
=> Create parent pom

tck/README.md
Fixes #165 
An initial draft of a README for the TCK to help users understand how to use and run the TCK.
=> Initial Draft of TCK README

tck/pom.xml
=> Explicity include default resource directory

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorServlet.java
=> Add leading slash to WebServlet annotation in DeploymentDescriptorServlet

tck-dist/pom.xml
=> Update version generation for the docs

api/pom.xml, pom.xml, tck/pom.xml
=> Execute unit tests in the build and fix scope for test dependencies

pom.xml
I updated the versions of the dependencies to the them used in Jakarta EE 10 Profiles.
I also changed the CDI compile type dependency to provided scope.
=> version of dependencies updated and CDI changed to provided

tck-dist/pom.xml
Note this still doesn't build as it expects 3.0.1 final releases to be available somewhere.
Is that how it is supposed to be?
=> Update pom versions for TCK-DIST job

tck-dist/src/main/artifacts/artifact-install.sh
Adding the version correction that @brideck made to the 3.0.1 TCK.
=> Update TCK version

api/pom.xml, pom.xml, tck/pom.xml
Merge in the 3.0.1 Release branch
=> Release 3.0.1

tck/src/main/java/ee/jakarta/tck/concurrent/common/counter/CounterSingleton.java
Addresses https://github.com/jakartaee/concurrency/issues/261
=> Reverts the EJB CounterSingleton to @Singleton

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/certification.yml, .github/ISSUE_TEMPLATE/clarification.yml, .github/ISSUE_TEMPLATE/tck-challenge.yml, .github/ISSUE_TEMPLATE/use-case.yml, .github/workflows/ci.yml, .gitignore
Creates a verification build to ensure we do not merge PRs that will break others. 
Also adds the standard templates required by the Jakarta EE platform.
=> Create verification build, and issue templates

tck/pom.xml, tck/src/main/java/ee/jakarta/tck/concurrent/framework/arquillian/extensions/TCKSignatureProcessor.java, tck/src/main/resources/ee/jakarta/tck/concurrent/common/signature/jakarta.enterprise.concurrent.sig_17, tck/src/main/resources/ee/jakarta/tck/concurrent/common/signature/jakarta.enterprise.concurrent.sig_21
Fixes #282 
DRAFT - wait until #279 is merged
=> Update signature tests for JDK 17 and 21

api/src/main/java/jakarta/enterprise/concurrent/CronTrigger.java, api/src/test/java/jakarta/enterprise/concurrent/CronTriggerTest.java, tck-dist/pom.xml, tck/README.md, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/tx/TransactionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/tx/TransactionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/tx/TransactionServlet.java
Cherry pick and recreate commits for a 3.0.3 service release.
Plan is to merge this onto branch RELEASE-3.0.2
Then, stage 3.0.3 artifacts which will create a new Github branch and tag for 3.0.3
Verify, TCK against Open Liberty
Finally, publish release
Related Issue #329
=> Create Service Release 3.0.3

.github/ISSUE_TEMPLATE/release.yml, tck/src/main/resources/ee/jakarta/tck/concurrent/common/signature/jakarta.enterprise.concurrent.sig_17, tck/src/main/resources/ee/jakarta/tck/concurrent/common/signature/jakarta.enterprise.concurrent.sig_21
=> Update signature files for M1 release

api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java
=> Refine `qualifier` defined via deployment descriptor and annotation attribute

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/application.xml, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/web.xml, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/ManagedThreadFactoryProducer.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/application.xml, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/web.xml
Fixes #404 
- Resolves outstanding TODOs for qualifier tests
- Fix some typos
- Verify if an application provides a default producer
- then the application will inject into the default injection point
- instead of the container injecting the default service.
=> Finalize tck qualifer tests

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextServiceDefinitionServlet.java
Adds TCK tests to cover contextualizing a Flow.Subscriber and Flow.Processor.
=> TCK updates for Flow

.github/workflows/ci.yml
This will get picked up by all future service branches created
=> Ensure future pulls and merges for service branches run CI build

api/pom.xml, api/src/test/java/jakarta/enterprise/concurrent/ContextServiceDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/CronTriggerTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedExecutorDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedExecutorsTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/ThreadContextProviderTest.java, api/src/test/java/jakarta/enterprise/concurrent/ThreadPriorityContextProvider.java, api/src/test/java/jakarta/enterprise/concurrent/ZonedTriggerTest.java
This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.
=> Migrate tests to JUnit5

api/etc/config/checkstyle.xml, pom.xml
=> Update checkstyle dependency

.github/workflows/ci.yml, .github/workflows/update.yml, tck/src/main/resources/ee/jakarta/tck/concurrent/common/signature/jakarta.enterprise.concurrent.sig_25
Add Java 25 to CI builds and upload an initial version of the java 25 signature file.
=> ci: add java 25-ea to builds
