jakartaee/concurrency

specification/pom.xml
The release job does not do this as it only operates on the api folder
=> Update spec pom version to match api pom version

api/pom.xml
specmode jakarta and jartype api no longer needed since default now.
Signed-off-by: arjantijms <arjan.tijms@gmail.com>
=> Updated spec version plug-in to 2.1

api/pom.xml, api/src/main/java/jakarta/enterprise/concurrent/ContextService.java, specification/src/main/asciidoc/jakarta-concurrency.adoc
fixes #100 
This pull copies over the method signatures from org.eclipse.microprofile.context.ThreadContext, except for withContextCapture because that is covered as a separate issue.  I'm also updating doc to clarify that if the
user doesn't pass in a serializable instance in the first place, there should be no expectation that we make the
proxy serializable.  Serializable isn't useful for completion stage actions, just adds overhead, and wasn't a
requirement of the equivalent methods in MicroProfile.
=> ContextService convenience methods for completion stages

api/pom.xml, api/src/main/java/jakarta/enterprise/concurrent/ContextService.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorService.java, specification/src/main/asciidoc/jakarta-concurrency.adoc
fixes #101 
This copies over the ThreadContext.withContextCapture(CompletionStage) and ThreadContext.withContextCapture(CompletableFuture) method signatures from MicroProfile Context Propagation 1.2 (latest version).  Also part of this approach is the ManagedExecutor.getThreadContext() method signature.  The Jakarta/Java EE Concurrency equivalent for MicroProfile's ThreadContext class is the ContextService, so I have added a ManagedExecutorService.getContextService() equivalent under this pull to have the same purpose, which is to obtain an instance that is backed by the managed executor so that the managed executor can be the default asynchronous execution facility for completion stages that created via withContextCapture.  I'm making note of this here because it's the only place thus …
=> completion stages backed by a context service

api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorService.java, specification/src/main/asciidoc/jakarta-concurrency.adoc
fixes #40 
This updates the ManagedExecutorService JavaDoc and adds the interface methods with identical signatures to MicroProfile's [ManagedExecutor](https://github.com/eclipse/microprofile-context-propagation/blob/master/api/src/main/java/org/eclipse/microprofile/context/ManagedExecutor.java)
A few updates were needed to the pom to build JavaDoc for Java SE 8, which introduces java.util.concurent.CompletableFuture and java.util.concurrent.CompletionStage which our interface methods are centered around.
=> CompletionStage backed by ManagedExecutorService

api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactory.java
This is the most I can see us doing for #46 
It should be noted that the same issue for parallel stream support was also opened in MicroProfile https://github.com/eclipse/microprofile-context-propagation/issues/10 where there isn't a ManagedThreadFactory equivalent, and there is a discussion there of a more granular approach that is already possible -- in both specs -- without these changes.
Also, reference [this gist](https://gist.github.com/NottyCode/9c1663f814ca7e579f9a05e13afda418) (I worked with the author on the concept behind it) of how a user can manually contextualize a ForkJoinWorkerThreadFactory using existing API.  This pull simply formalizes that approach in declaring that the ManagedThreadFactory will provide it for you by also implementing the ForkJoinWorkerThreadFactory …
=> managed ForkJoinWorkerThreadFactory for parallel stream operations with context

api/pom.xml, api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java, api/src/test/java/jakarta/enterprise/concurrent/ContextServiceDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedExecutorDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinitionTest.java, api/src/test/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinitionTest.java
This pull is the first step toward #38
It creates resource definition annotations:
`@ContextServiceDefinition`
`@ManagedExecutorDefinition`
`@ManagedScheduledExecutorDefinition`
`@ManagedThreadFactory`
along with a handful of attributes for each - hopefully the most basic ones that will be common across implementations and therefore non-controversial.  More can certainly be added in follow-on pulls.  I have not marked this pull to close out the issue, so that separate pulls will still be able to further build on top of this, adding in whatever other config is agreed upon.
Actions to accomplish after this pull goes in:
- add more attributes
- create corresponding `<context-service>`, `<managed-executor>`, `<managed-scheduled-executor>`, `<managed-thread-factory>` definitions in deployment …
=> create resource definition annotations for Concurrency

api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java
When any of the other resource definitions refer to a context service definition by its name, the behavior is clear if the context service name is as granular or less granular than the other resource definition's name.  For example,
```
<managed-executor>
<name>java:app/concurrent/executor1</name>
<context-service-ref>java:app/concurrent/myContext1</context-service-ref>
</managed-executor>
<managed-executor>
<name>java:app/concurrent/executor2</name>
<context-service-ref>java:global/concurrent/myContext2</context-service-ref>
</managed-executor>
```
However, the behavior is unclear if referring to a context service definition with a more granular name, such as,
```
<managed-executor>
<name>java:app/concurrent/myExecutor</name>
<context-service-ref>java:comp/concurrent/myContext</context-se …
```
=> Issue #38 ambiguity with more granular names

api/src/main/java/jakarta/enterprise/concurrent/CronTrigger.java, api/src/test/java/jakarta/enterprise/concurrent/CronTriggerTest.java
To avoid possible overflow, advancement needs to be done by the ZonedDateTime.plus method rather than setting a computed amount that might be out of range.
=> prevent overflow when advancing trigger

api/src/main/java/jakarta/enterprise/concurrent/Asynchronous.java
I noticed this while adding the signature tests. It's currently possible for someone to write code that creates an instance of the Asynchronous.Result class, which is pointless.  This class is only intended to provide static methods for managing the result of asynchronous methods.  We should declare the default constructor private to prevent constructing instances and keep it out of the JavaDoc.
=> Prevent instantiation of Asynchronous.Result

api/README.md, api/src/main/java/jakarta/enterprise/concurrent/ContextService.java
Clarification on when context is captured for the ContextService methods.
=> ContextService update

api/src/main/java/jakarta/enterprise/concurrent/Asynchronous.java
checkstyle is complaining that Asynchronous.Result needs to be declared final because its only constructor is private. This pull makes that update so that we won't see this warning when building the project.
=> Fix checkstyle error for Asynchronous.Result

api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java
I found an example helped me understand when unchanged is relevant and how it differs from cleared and propagated.
Rendered JavaDoc after the change:
=> Adding example to ContextServiceDefinition.unchanged()

tck/src/main/java/ee/jakarta/tck/concurrent/signature/SignatureTestServlet.java, tck/src/main/resources/WEB-INF/signaturetest/jakarta.enterprise.concurrent.Asynchronous.sig, tck/src/main/resources/WEB-INF/signaturetest/jakarta.enterprise.concurrent.ContextServiceDefinition.sig
Don't rely on annotation toString in the signature tests because its output is not standard and differs between JDKs.  The toString output was being used by the TCK as a shortcut for comparing the annotations on the method/class, which would have been nice if were a standard, but since it isn't, we need to replace this shortcut with a different approach that is more reliable.
=> annotation toString differs between JDKs

tck/pom.xml
Currently, we have files like `web.xml` and  `class.sig` files within the same package as the test class they are associated with to better aid in readability and encapsulation.  However, not all maven versions will automatically package non-class resources located within packages into the published artifact. This PR will ensure that these files are included.
=> Ensure TCK includes non-class resources

api/src/main/java/jakarta/enterprise/concurrent/CronTrigger.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorService.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedTaskListener.java, specification/pom.xml, specification/src/main/asciidoc/jakarta-concurrency-spec.adoc, specification/src/main/asciidoc/jakarta-concurrency.adoc, specification/src/main/asciidoc/license-efsl.adoc, tck/pom.xml
After switching to Java 11 to build the tck, I realized that the api and specification builds fail with Java 11.
In the case of /specification/, it's just an artificial limitation imposed by requireJavaVersion which we can easily relax.
In the case of /api/, there are these errors with the JavaDoc using some no-longer-available HTML attributes,
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project jakarta.enterprise.concurrent-api: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - /Users/njr/lgit/concurrency-api/api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorService.java:89: error: attribute not supported in HTML5: summary
[ERROR]  * <table summary="Task Lifecycle"> …
```
=> Allow building with Java 11

api/pom.xml
Avoid ending up with bnull and null in MANIFEST.MF of the API jar by setting the property in the pom to indicate that this will be a final release.
Here is the sort of versions we got before:
```
Bundle-Version: 2.0.99.bnull
Export-Package: jakarta.enterprise.concurrent;version="2.0.99.bnull";u
ses:="jakarta.enterprise.util,jakarta.interceptor",jakarta.enterprise
.concurrent.spi;version="2.0.99.bnull"
...
Specification-Version: 2.0.99.null
```
After making this change locally, I get the following instead:
```
Bundle-Version: 3.0.0
Export-Package: jakarta.enterprise.concurrent;version="3.0.0";uses:="j
akarta.enterprise.util,jakarta.interceptor",jakarta.enterprise.concur
rent.spi;version="3.0.0"
...
Specification-Version: 3.0
```
=> Set the property to indicate a final release so that MANIFEST.MF gets correct versions

tck/README.md
The Spec Review Checklist requires that the TCK User's Guide document where to file challenges to the TCK.
This pull adds that.  I have also updated its title to clarify that it is the TCK User's Guide
and have corrected terminology that should refer to a _candidate_ to become a compatible implementation rather than calling something a compatible implementation before the TCK and specification are declared final.
@edbratt also informed me that the rules from Section 2.2.2 of the Concurrency 2.0.1 TCK User Guide should not have been dropped without the spec group making the decision to do so.  This was done by accident in that they were never ported over and this pull adds them back in word for word.  Post EE 10, some consideration can be given as to whether anything else within the old …
=> Document where to file TCK challenges

pom.xml, tck-dist/EFTL.txt, tck-dist/README.md, tck-dist/artifact-install.sh, tck-dist/pom.xml, tck-dist/src/main/assembly/assembly.xml, tck/pom.xml, tck/src/main/resources/concurrency-api-jdk11.sig
Here is an example module that can be run after the TCK has been staged to create a dist bundle usable for the EE10 release. I have also added a signature map file and signature-generation profile to create it as I did not see this discussed in the TCK user guide. How to run the signature tests against the OpenLiberty compatible implementation still needs to be added to the CK user guide.
=> Example tck-dist bundle build

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorTestBean.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorTestBeanInterface.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/application.xml
A recent discussion with on the mailing list with @smillidge "Javadoc implies a deployment descriptor" reminded me that tests for the new deployment elements (such as `<managed-executor>` and `<context-service>`) need to be added for platform coverage.  But since the old platform TCK is being removed, and because there's still a little bit of time for us to get updates into the new TCK in the Concurrency project while the signature tests are being cleaned up, I've created this pull to add these deployment descriptor element tests here, which should then make it unnecessary to add to the platform TCK, hopefully making that removal effort smoother.
=> test new resource definition elements in deployment descriptor

tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedExecutors/ManagedExecutorsServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedScheduledExecutorService/ManagedScheduledExecutorServiceServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ClassloaderServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextServiceDefinitionFromEJBServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextServiceDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/JNDIServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/JSPSecurityServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/SecurityServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate_servlet/DeserializeServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate_servlet/ProxyCreatorServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate_servlet/WorkInterfaceServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/tx/TransactionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/inheritedapi/CommonServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/managed_servlet/forbiddenapi/ForbiddenServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionOnEJBServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/security/SecurityServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi_servlet/InheritedAPIServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionOnEJBServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/security/SecurityServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/tx/TransactionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/apitests/APIServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/context/SecurityServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/context_servlet/ContextServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/resourcedef/ManagedThreadFactoryDefinitionOnEJBServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/resourcedef/ManagedThreadFactoryDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/tx/TransactionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/signature/SignatureTestServlet.java
Reason:
The servlet spec tells nothing about the leading slash, but all examples contain it.
https://github.com/jakartaee/servlet/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc#811-webservlet
=> Add leading slash to @WebServlet annotations

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/context/ContextTests.java
ContextTests is a broken test, it tries to deploy classes SecurityTestEjb and SecurityTestRemote in both jar and war inside one ear.
=> fix ContextTests deployment, put ejb classes only into jar

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/tx/Constants.java
Fixed one forgotten WebServlet annotation without leading slash.
=> add leading slash to WebServlet annotation in TransactionServlet

tck/README.md, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/SigTestEE.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/SignatureTestDriver.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/signature/ConcurrencySigTest.java, tck/src/main/resources/ee/jakarta/tck/concurrent/spec/signature/sig-test.map
Addresses comment in #195 to remove the remaining occurrence of a spec version number from files within the Concurrency TCK.  This will make for a seamless transition between spec releases and will be one less place where developers need to know that they must manually update a version number.
Also, I fixed a broken link in the signature test section of the readme.
=> Remove remaining version from signature tests

CONTRIBUTING.md, NOTICE.md, api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java, pom.xml, tck/README.md
Various files have hard-coded links to the old eclipse-ee4j/concurrency-api repository. Update these to point at the new location: jakartaee/concurrency
=> update hard-coded locations of concurrency repo

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextServiceDefinitionBean.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextServiceDefinitionFromEJBServlet.java
Code for an unreachable test case was found in the Concurrency TCK.  It appears to have been copied from a test of the same name in the web module, probably used as a starting point for writing tests for EJBs.  Other dead code was identified and removed back when those tests were added and this might have been missed in the respect that it was more dead code or missed in that it was never finished and enabled.  At this point, we could either remove the test or correct it in a couple of places and enable it.  I have created pulls for both and the community can choose.  This pull is to correct it and enable the test. The other one is #199.
=> Fix and enable broken copied TCK test

api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java
Clarifications to ContextServiceDefinition JavaDoc for ALL_REMAINING and TRANSACTION constants that were discussed on the mailing list thread for ContextServiceDefinitionServlet.testContextServiceDefinitionDefaults.
=> JavaDoc clarifications from the testContextServiceDefinitionDefaults discussion

api/pom.xml
While updating the pull for the release review with the latest, I noticed the following on generated JavaDoc for the Concurrency API,
```
Jakarta Concurreny API v3.0.0
```
and
```
Copyright (c) 2020, ${current.year} Eclipse Foundation.
```
This pull corrects the above.
=> Spec name misspelled and copyright year variable not expanded in generated JavaDoc

api/pom.xml
It would have been nice to include this under my previous pull, but I hadn't spotted it yet.
Generated JavaDoc is redundant in stating API twice in lots of places, such as these,
```
<title>Overview (Jakarta Concurrency API 3.0.0 API)</title>
```
```
<h1 class="title">Jakarta Concurrency API 3.0.0 API</h1>
```
=> Generated JavaDoc redundantly refers to API 3.0.0 API

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationTests.java
As brought up on the mailing list by @aubi the behavior of HttpServletRequest.getUserPrincipal is unclear when running on a different thread or the current user is switched. We cannot have tests that rely on a particular behavior there and so are disabling the 2 tests that were using it because these tests don't do anything else of significance.
=> Disable new tests relying on uncertain behavior of getUserPrincipal

tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc
Make the update requested by @edbratt on the Concurrency mailing list review of the TCK zip,
> I think I would caution against including Kayle's e-mail in the reference guide doc. Perhaps it would be better to suggest feedback be sent to the e-mail list instead ([cu-dev@eclipse.org](mailto:cu-dev@eclipse.org)). Keep the author name, just not the e-mail address.
=> Switch TCK reference guide email to the spec mailing list

tck-dist/src/main/artifacts/artifact-install.sh
Our developer trying out the TCK from the zip artifact (rather than the maven jar which we had been using to this point) found that `artifact-install.sh` contains an unexpanded variable,
```
VERSION=${jakarta.concurrent.version.ga}
```
I suspect the intent was for the build to replace that.  For now, the quickest solution is to just hard code it.
=> jakarta.concurrent.version.ga variable not being replaced in TCK artifact

tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc, tck-dist/src/main/starter/pom.xml
The documentation on the server dependencies was misleading and did not expressly tell users to use a profile for this work.
Instead, let's simplify our instructions by removing the need for a profile, and give instructions on how to copy dependencies using a separate command. 
Also fixing a misplaced `<dependency>` tag
=> Fix TCK documentation on server dependencies

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/resourcedef/ManagedThreadFactoryDefinitionOnEJBServlet.java
Obvious copy&paste error:
txTaskResult -> lookupTaskResult.completeExceptionally()
Ad java:comp usage: is there any particular reason to use it in this test? I has a specific behavior in web app (equal to module), but EJB-bound in EAR app. If we want to use it, it must be kept EJB-bound, e.g. lookup it in the managedThreadFactoryDefinitionBean. Personally, I would prefer to use java:app as it makes me better sense to define thread factory for whole app.
=> Fix managedthreadfactory component context

tck/src/main/java/ee/jakarta/tck/concurrent/api/Trigger/TriggerTests.java
The counter wasn't reset before tests, running other tests influence this one.
I will follow the challenge process.
=> add forgotten counter reset before tests

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/security/SecurityTests.java
Removing duplicate classes SecurityTestRemote and SecurityTestEjb from war, because they are already in jar. Same classes cannot be in both archives inside one ear application.
Same as https://github.com/jakartaee/concurrency/pull/218, just different test.
I will follow the challenge process.
=> FISH-6216-fixing-binding-issue-for-class-duplication

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/security/SecurityTests.java
This is to remove duplicate EJB definition classes from the arquillian deployment configuration
=> removing duplicate EJB definition classes

api/pom.xml
Fixes Jenkins Build Error
```
[INFO] --- spec-version-maven-plugin:2.1:check-module (default) @ jakarta.enterprise.concurrent-api ---
[ jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api:3.0.1-SNAPSHOT ]
{ groupIdPrefix=jakarta. spec-version=3.0 apiPackage=jakarta.enterprise.concurrent API final spec-impl-version=3.0.0 }
- WARNING: Implementation-Version (3.0.0) should be equal to Maven-Version (3.0.1)
- WARNING: Bundle-Version (3.0.0) should be 3.0.1
```
=> Fix build failure on mismatch on spec impl version

api/pom.xml, pom.xml, specification/pom.xml, tck-dist/pom.xml, tck-dist/src/main/starter/pom.xml, tck/pom.xml
* Fix mixed whitespace - now all spaces
* Formatting
* Elements in Maven preferred order
* Updated versions
* Updated specification configuration according to asciidoc 2.0+
* Added flatten plug-in for API
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>
=> Tidying poms

api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java, tck/pom.xml, tck/src/main/java/ee/jakarta/tck/concurrent/framework/TestUtil.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/SigTest.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/SigTestEE.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/SignatureTestDriver.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionBean.java
=> Fix TCK JavaDoc

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationTests.java
After accepting the challenge https://github.com/jakartaee/concurrency/issues/253, the test should be disabled.
=> Disable Challeged testContextualFunction

tck-dist/pom.xml, tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc, tck-dist/src/main/assembly/assembly.xml, tck-dist/src/main/starter/pom.xml, tck-dist/src/main/starter/suite-web.xml, tck/pom.xml
An extra suite.xml file was added to the starter module to test the
web-profile. The guide was updated to mention this.
Since the API version of Concurrency (e.g. 3.0.1) and the TCK version
(e.g. 3.0.2) don't necessarily have to be the same, the properties for
these were renamed to make it more clear which is which.
Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>
=> Add suite file for web and make tck/api versions clear

tck-dist/src/main/starter/suite.xml, tck/src/main/java/ee/jakarta/tck/concurrent/common/TestGroups.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/EJBJNDIProvider.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextEJBProvider.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextPropagationWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/ContextServiceDefinitionWebBean.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ContextService/contextPropagate/TestSecurityRunnableWork.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/security/SecurityEJBProvider.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/security/SecurityTestTask.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/security/SecurityTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/security/SecurityWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi/CounterEJBProvider.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi/InheritedAPIWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi/TestEjb.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/security/SecurityEJBProvider.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/security/SecurityTestTask.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/security/SecurityWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/context/ContextWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedThreadFactory/resourcedef/ManagedThreadFactoryDefinitionWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/web.xml
Fixes #244 
I went ahead and duplicated the test classes that currently can only run on Full profile because they package tests as EARs, and packaged them as WEB archives instead.  I then disabled tests where they didn't make sense to run on Web Profile. 
I also had to make some modifications due to the way that we passed EJB JNDI names between the test classes and the application running on the server.  I did this by introducing an SPI that will provide the JNDI name depending on if we are running in Full Profile vs Web Profile. 
Here are the results of testing this against Open Liberty:
=> Update TCK for web profile

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionWebBean.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionWebBean.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionWebTests.java
Fixes #263 
This is required for Web profile testing because in the following packages there are two EJBs that both register the same ManagedExecutorDefinition at the JNDI scope of `java:module` which was missed when originally separating the Full profile and Web profile tests.  In the following sections, I have created lists of the context services and managed executors for these packages to show the updated state of these tests in a way that is easier to understand than the Arquillian packaging alone.
```java
@List({
@ContextServiceDefinition(name = "java:app/concurrent/ContextA", propagated = {"Application", "IntContext"}, cleared = {"StringContext"}, unchanged = {"Transaction"}),
@ContextServiceDefinition(name = "java:module/concurrent/ContextB", cleared = {"Transaction"}, unchanged = …
```
=> avoid duplicate managed executor definitions

api/pom.xml, pom.xml, tck-dist/pom.xml, tck/pom.xml
=> Update for 3.1 spec development cycle

api/src/main/java/jakarta/enterprise/concurrent/CronTrigger.java, api/src/test/java/jakarta/enterprise/concurrent/CronTriggerTest.java
Fixes #274 ArrayIndexOutOfBoundsException that occurs because some code for detecting Daylight Saving Time was erroneously being attempted for a non-matching hour.
=> ArrayIndexOutOfBoundsExeption from DST code

.github/workflows/ci.yml
The main branch was re-named after the CI file was created. 
Fixing the branch name.
=> Fix branch name in concurrency CI

.github/dependabot.yml, .github/workflows/ci.yml, api/pom.xml, pom.xml, tck-dist/pom.xml, tck-dist/src/main/assembly/assembly.xml, tck/pom.xml
Fixes #285 #297 #298 from dependabot
Also fixes some build breaks that were not caught by the CI build. 
- Updated CI build to build the SPEC and TCK-DIST modules
- Fixed TCK-DIST that didn't know about the new signature files
=> Update dependabot and CI build

api/src/main/java/jakarta/enterprise/concurrent/CronTrigger.java, tck/README.md
Fixes #318
Clarifies some of the variables in CronTrigger for better readability.
=> Refactoring CronTrigger variable names

api/src/main/java/jakarta/enterprise/concurrent/Trigger.java
Fixes #33 by copying from the more clear ZonedTrigger JavaDoc to replace the corresponding unclear parts of the Trigger Javadoc.
=> clarifications to Trigger JavaDoc

.github/dependabot.yml, specification/pom.xml
- Manual update to jruby dependency, since the latest is incompatible
- Removing the submodules from the dependabot.yml, since I believe this is causing duplicate PRs to be opened, and dependabot should scan submodules automatically.
=> Dependencies updates

README.adoc
When the README was switched from Markdown to AsciiDoc the links were not switched to the AsciiDoc format, this pr changes the links to AsciiDoc format.
=> Correcting links to adoc format in README

.github/dependabot.yml
Since we're using GH Actions on PRs, we should include that in our dependabot scanning.
=> Adding github actions to dependabot scanning

api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java
fixes #268
This pull adds the virtual=true hint to request the use of virtual threads to ManagedThreadFactoryDefinition, ManagedExecutorDefinition, and ManagedScheduledExecutorDefinition.  The default is false.
Regarding the discussion on the name of the attribute, `virtual` is used because it matches the terminology and hard-coded method names of the java.lang.Thread API, which has methods like [isVirtual](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#isVirtual()) and [ofVirtual](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.html#ofVirtual()).
=> hint to request virtual threads

tck/src/main/java/ee/jakarta/tck/concurrent/api/ContextService/ContextServiceTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedExecutors/ManagedExecutorsTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedScheduledExecutorService/ManagedScheduledExecutorServiceTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedTask/ManagedTaskTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedTaskListener/ManagedTaskListenerTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/SkippedException/SkippedExceptionTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/Trigger/TriggerTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionFullTests.java
Fixes #178 
No one in this repository nor on the mailing list has raised any opposition to running our API tests only in a servlet and not repeating them using Enterprise Beans or Pages.
=> Remove TODOs from TCK that are invalid

tck/src/main/java/ee/jakarta/tck/concurrent/api/LastExecution/LastExecutionTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/api/Trigger/TriggerTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/common/fixed/counter/StaticCounter.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/junit/extensions/Wait.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/inheritedapi/InheritedAPITests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi/InheritedAPIServletTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi/TestEjb.java
Fixes #258
Removed `Wait.waitTillFutureIsDone()` because it was misleading.
Fixed the issues where it was being used incorrectly. 
Everywhere else has been switched to `Wait.waitForTaskComplete()`
=> Invalid assertion in LastExecutionTests

api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java
Fixes the [issue](https://github.com/jakartaee/concurrency/pull/348/files/e743973a54e2a5f1354e9592824f398026b67c6d#r1341093857) found by @OndroMih where `qualifiers = MyQualifier.class` was accidentally omitted from the JavaDoc example.
=> missed qualifiers in resource definition example

specification/pom.xml
Bumping the jruby dependency to 9.3.11.0. The 9.4 stream is still not compatible with the latest asciidoctorj
=> Updating jruby dependency

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/certification.yml, .github/ISSUE_TEMPLATE/clarification.yml, .github/ISSUE_TEMPLATE/release.yml, .github/ISSUE_TEMPLATE/tck-challenge.yml, .github/ISSUE_TEMPLATE/use-case.yml, .github/dependabot.yml, .github/workflows/ci-pull.yml, .github/workflows/ci-push.yml, .github/workflows/ci.yml, .github/workflows/release.yml, tck-dist/src/main/artifacts/artifact-install.sh, tck/README.md, tck/pom.xml, tck/src/main/java/ee/jakarta/tck/concurrent/common/signature/ConcurrencySignatureTestRunner.java, tck/src/main/java/ee/jakarta/tck/concurrent/common/signature/README.md, tck/src/main/java/ee/jakarta/tck/concurrent/framework/arquillian/extensions/TCKArchiveProcessor.java
This PR does the following housekeeping for the Concurrency project:
- Updates the CI builds to use Java 21 GA (instead of EA)
- Updates issue templates to be valid YML
- Adds a release template that will make it easier to keep track of tasks needed to create a release
- Adds a workflow that will automatically update our issue templates with updated versions
- Updates the signature file generation task to automatically copy and rename the signature file into the TCK resources.
- Creates a workflow that will automatically open a PR to update the signature files when updates to API are merged.
- Removes the requirement for updating the signature test based on Jakarta + JDK version support (instead we can just assume if a signature file for a certain JDK version doesn't exist then it isn't …
=> Concurrency project housekeeping

api/src/main/java/jakarta/enterprise/concurrent/ContextService.java
I'm looking to get feedback on adding these two new APIs to Context Service. After investigation the Flow classes added in Java 9, what I believe would be the most useful addition for Concurrency is providing context on the Flow.Subscriber methods. The new Flow class consists of:
- `Flow.Publisher`
- `Flow.Subscription`
- `Flow.Subscriber`
- `Flow.Processor`
From what I can tell, `Flow.Publisher`'s methods would generally be invoked where context is available, and `Flow.Subscription` doesn't have methods where context would add value. `Flow.Subscriber` is where context could be useful, because it's methods may or may not be called asynchronously. `Flow.Processor` extends `Flow.Publisher` and `Flow.Subscriber`, which is why I provided an API to contextualize it's `Flow.Subscriber` methods. …
=> Adding Flow Subscriber APIs to ContextService

specification/src/main/asciidoc/jakarta-concurrency.adoc
Spec additions to match  #368 plus a few minor spec fixes
=> Spec updates for Flow

tck/pom.xml
The release build swaps out versions numbers.
If a hard-coded version is missed it causes build errors. 
Related #377
=> Avoid using hard coded versions in subprojects

tck-dist/pom.xml, tck-dist/src/main/assembly/assembly.xml
The maven-assembly-plugin failed to include the parent pom in the assembled tck-dist.jar because the parent pom was not declared as a dependency.  
Not sure if this was a behavior change with the plugin, but I've added in a specific plugin version so we can keep up to date and fixed the assembly.xml file to reflect the artifacts we actually include.  It doesn't seem like the tck source jar has ever been included correctly.
=> TCK distribution failed to include parent pom

api/src/main/java/jakarta/enterprise/concurrent/ManageableThread.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactory.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java, specification/src/main/asciidoc/jakarta-concurrency.adoc
This pulls updates spec documentation with some additional limitations that will apply if using virtual threads. This includes the inability to use a thread priority other than the default NORM_PRIORITY (5) and that a virtual thread from a ManagedThreadFactory cannot be expected to implement `ManageableThread` because Java restricts creation of virtual threads to its own builders, preventing virtual threads from implementing custom interfaces such as this.
=> document additional limitations if using virtual threads

tck/src/main/java/ee/jakarta/tck/concurrent/common/qualifiers/CustomQualifier1.java, tck/src/main/java/ee/jakarta/tck/concurrent/common/qualifiers/CustomQualifier2.java, tck/src/main/java/ee/jakarta/tck/concurrent/common/qualifiers/InvalidQualifier3.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/junit/anno/Assertion.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/junit/anno/Challenge.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/junit/anno/Debug.java, tck/src/main/java/ee/jakarta/tck/concurrent/framework/junit/anno/TestName.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/application.xml, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/web.xml
=> Add qualifier tests for Deployment Descriptors

api/src/main/java/jakarta/enterprise/concurrent/ContextServiceDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java, specification/src/main/asciidoc/jakarta-concurrency.adoc
We need to add more information to the Concurrency spec on the new pattern with qualifiers, such as what scope the injected bean should be.  ApplicationScoped seems appropriate given other requirements in the spec to make the life cycles of concurrency managed objects align with the application's life cycle.  We should also include a short example qualifier/inject and document any other limitations, such as that the qualifier annotation will either need to have no attributes or have all attributes defaulted.
=> document scope for beans, qualifier limitations and example

specification/src/main/asciidoc/license-efsl.adoc
The Jakarta Concurrency specification document still shows 2022 as the copyright year (which would have been the case for Concurrency 3.0). This pulls updates it to 2024.
=> Update specification copyright year to 2024

specification/src/main/asciidoc/jakarta-concurrency.adoc
The Concurrency specification references numbered sections of the Jakarta EE platform specification and of its own specification.  In several cases, it appears that the numbering of these sections has changed, or in some cases 5 levels of numbering were used where the referenced document only has 4 levels.  This pull makes corrections.
=> Update out-of-date references in spec

specification/src/main/asciidoc/jakarta-concurrency.adoc
The pull contains various grammar and formatting fixes to the Concurrency specification document.
One category of formatting errors is with the use of checked and empty checkboxes, with the former rendering improperly (as a square with a question mark inside) and the latter not showing at all.
=> Various grammar and formatting fixes to the specification document

specification/src/main/asciidoc/jakarta-concurrency.adoc
Fix the following asciidoctor warnings that appear when building the spec doc:
```
[INFO] asciidoctor: WARN: jakarta-concurrency.adoc: line 2440: section title out of sequence: expected level 2, got level 4
[INFO] asciidoctor: WARN: jakarta-concurrency.adoc: line 2461: section title out of sequence: expected level 2, got level 4
[INFO] asciidoctor: WARN: jakarta-concurrency.adoc: line 2485: section title out of sequence: expected level 2, got level 4
[INFO] asciidoctor: WARN: jakarta-concurrency.adoc: line 2653: section title out of sequence: expected level 2, got level 3
[INFO] asciidoctor: WARN: jakarta-concurrency.adoc: line 2664: section title out of sequence: expected level 2, got level 3
[INFO] asciidoctor: WARN: jakarta-concurrency.adoc: line 2748: section title out of sequence: …
```
=> Fix errors with asciidoc section headers

.github/workflows/ci.yml, api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorService.java
Changes the CI to run on both Java 17 and 21, following the change to Jakarta EE 11 to support both Java versions.
Minor typo fixes in ManagedExecutorService Javadoc
=> Re-enable java 17 CI builds

tck/src/main/java/ee/jakarta/tck/concurrent/common/qualifiers/OverwrittenQualifier4.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/application.xml
When writing tests for `qualifier` I wrote a test that is invalid.
Based on the Concurrency javadoc:
https://github.com/jakartaee/concurrency/blob/357c45e284e1a44783209608e92c8ed27e1705ef/api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java#L93-L99
I assumed that meant that a deployment descriptor in `application.xml` would merge/override values defined on the class annotation `@ManagedThreadFactoryDefinition`. 
This was the wrong assumption based on the platform spec: 
https://github.com/jakartaee/platform/blob/29bf7cc3266097d3b68d8d849ccd01eefbae9a1b/specification/src/main/asciidoc/platform/ApplicationAssemblyDeployment.adoc?plain=1#L1069-L1081
Which seems to indicate that `metadata-complete` is what defines whether or not merging should happen between …
=> Remove override via application.xml test

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/clarification.yml, .github/ISSUE_TEMPLATE/release.yml, .github/ISSUE_TEMPLATE/tck-challenge.yml, .github/ISSUE_TEMPLATE/use-case.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/update.yml
This PR updates the following: 
- Issue template descriptions to be more specific to help users choose which template to use.
- General formatting of issue templates
- Switch CI workflow from `install` to `package` for performance
- Ensure release workflow uses correct branch
- Ensure update workflow runs and only commits files we expect to be changed (for better security)
This PR should likely be merged after https://github.com/jakartaee/concurrency/pull/426 to avoid merge conflicts.
=> Update workflows and issues

api/src/main/java/jakarta/enterprise/concurrent/ManagedExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedScheduledExecutorDefinition.java, api/src/main/java/jakarta/enterprise/concurrent/ManagedThreadFactoryDefinition.java
Remove Java SE 21 usage from API so that it will be possible to compile against Java SE 17 as is being required by the platform.
=> API updates to support Java SE 17

.github/workflows/ci.yml, api/pom.xml, pom.xml
=> Update dependencies to Jakarta EE 11 ones

api/src/main/java/jakarta/enterprise/concurrent/Asynchronous.java
=> Clarify scheduled asynchonous methods with return type of void

tck/src/main/java/ee/jakarta/tck/concurrent/api/ManagedThreadFactory/ManagedThreadFactoryTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/inheritedapi/InheritedAPITests.java
Some tests are failing, because the static counter is set by previous tests. Simple reset of the counter before tests fixes it.
=> Fix Tests Depending on Static Counter by Resetting Before Tests

api/src/main/java/jakarta/enterprise/concurrent/Asynchronous.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/AppBean.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionFullTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionWebTests.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ReqBean.java
=> Add scheduled async tests

tck/src/main/java/ee/jakarta/tck/concurrent/framework/junit/extensions/Wait.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/inheritedapi/TestEjb.java
The framework package is delivered as a jar in /lib/jakarta-concurrent-framework.jar, although it depends on test class CounterInterface, depolyed in /inheritedapi.jar.
This change removes this dependency by calling the counter via `Supplier`.
=> Remove Dependency from Framework to Tests

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/virtual/VirtualThreadServlet.java
Found an issue with the virtual tests when using Java 17.  Attempted to call the `isVirutal()` method on Java 17 resulting in NoSuchMethodException
=> Fix virtual tests for Java 17

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationFullTests.java
With the current setup, the deployment ends with WELD error Unable to identify the correct BeanManager. The calling class ee.jakarta.tck.concurrent.spec.Platform.anno.AnnotationServlet is not placed in bean archive
=> Fix AnnotationFullTests, Make WAR File a Bean Archive

api/src/main/javadoc/doc-files/speclicense.html, specification/src/main/asciidoc/license-efsl.adoc
As discussed here: https://github.com/jakartaee/specifications/pull/733
=> Update license for Jakarta EE 11

tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc, tck-dist/src/main/java/ee/jakarta/tck/data/metadata/CollectMetaData.java
As discussed here: https://github.com/jakartaee/specifications/pull/733
The test counts in the TCK documentation were misleading: 
- Documented - `[WARNING] Tests run: 268, Failures: 0, Errors: 0, Skipped: 27`
- Reality           - `[WARNING] Tests run: 295, Failures: 0, Errors: 0, Skipped: 27`
I made the false assumption that the Tests Run did not include skipped tests, when in reality the skipped tests are double counted.
=> Clarify test counts in TCK documentation

.github/ISSUE_TEMPLATE/release.yml, .github/workflows/specification.yml, api/README.md, api/pom.xml, specification/README.md, specification/pom.xml, tck/README.md
Gathers all materials needed for specification project release review and packages them
=> Help automate specification project release review

.github/ISSUE_TEMPLATE/certification.yml, tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc
SHA checksum for individual TCKs should be run on the TCK jar and not the TCK distribution zip.
=> Update certifcation documentation

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/anno/AnnotationServlet.java
The servlet `AnnotationServlet` turned into an `Dependent` CDI bean so that it's scanned by a CDI extension, which can then read the definitions from the annotations.
I decided to use `@Dependent` scope because Servlet spec version 3.0 explicitly forbids other CDI scopes for servlets. Some servers still abide this even though it seems this restriction was removed in newer Servlet spec versions. Concurrency TCK should not contain any assertions for other specs, so I use widely accepted `@Dependent`.
Fixes #489
=> AnnotationFullTests adds resource definitions with qualifiers on a CDI bean

tck/src/main/java/ee/jakarta/tck/concurrent/spec/Platform/dd/DeploymentDescriptorServlet.java
Adding the same annotation as in https://github.com/jakartaee/concurrency/pull/491
DeploymentDescriptorFull/WebTests are basically the same tests as AnnotationFull/WebTests, just requiring loading the definitions from xml files.
=> DeploymentDescriptorFull/WebTests Adds Resource Definitions with Qualifiers on a CDI Bean

tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedExecutorService/resourcedef/ManagedExecutorDefinitionServlet.java, tck/src/main/java/ee/jakarta/tck/concurrent/spec/ManagedScheduledExecutorService/resourcedef/ManagedScheduledExecutorDefinitionServlet.java
I removed tests of context switch, which tested, that the context capture happened during jndi lookup. The test later setup number 22 and the test checks, if asynchronous method (running via scheduler) returns 0.
The code:
```
ManagedExecutorDefinitionFullTests.testScheduledAsynchIgnoresMaxAsync() {
...
IntContext.set(22); //Context should be cleared
CompletableFuture<Integer> future = reqBean.scheduledEvery3Seconds(1, counter);
...
assertEquals(Integer.valueOf(0), future.get(MAX_WAIT_SECONDS, TimeUnit.SECONDS),
"ManagedScheduledExecutorService with maxAsync=4 must be able to run scheduled async methods concurrently.");
```
`reqBean.scheduledEvery3Seconds` runs only once and returns `IntContext`: `future.complete(IntContext.get())`
1. There is no explicit setup of the IntContext value to …
=> Removing Tests of Context Switch from Asynchronous Tests

.github/workflows/ci.yml, tck-dist/src/main/asciidoc/concurrency-tck-reference-guide.adoc, tck-dist/src/main/starter/pom.xml, tck/pom.xml, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/README.md, tck/src/main/java/ee/jakarta/tck/concurrent/framework/signaturetest/SigTestDriver.java, tck/src/main/resources/ee/jakarta/tck/concurrent/spec/signature/jakarta.enterprise.concurrent.sig
Fixes #392
Fixes #393
Alternative solution for continued support of the Concurrency 3.0 TCK for future LTS Java levels.
Start using the jakarta.tck signature test plugin which allows for blanket ignoring of jdk classes.
Tested using Open Liberty on Java 17 (semeru) and Java 21 (openjdk): 
```txt
********************************************************************************
product = Open Liberty 24.0.0.6 (wlp-1.0.91.202406061535)
java.home = /Library/Java/JavaVirtualMachines/semeru-17.jdk/Contents/Home
java.version = 17.0.7
java.runtime = IBM Semeru Runtime Open Edition (17.0.7+7)
os = Mac OS X (14.5; aarch64) (en_US)
********************************************************************************
...
[6/27/24, 16:04:34:148 CDT] 00000091 …
```
=> Use jakarta.tck:sigtest-maven-plugin in 3.0 service stream

pom.xml
Updates the parent pom for this project from 1.0.6 -> 1.0.9 in the 3.0 service branches.
This is required for our staging and release builds.
The nexus-staging-maven-plugin dependency from the parent project needs to be upgraded from 1.6.8 -> 1.6.13 to support Java modules. 
```
[ERROR] -----------------------------------------------------: Unable to make field private final java.util.Comparator java.util.TreeMap.comparator accessible: module java.base does not "opens java.util" to unnamed module @46c3a14d
```
=> Update concurrency 3.0 service stream parent

pom.xml, specification/pom.xml, tck-dist/pom.xml
The TCK distribution needs to be available in the staging repository before it can be uploaded to the eclipse.org staging site.
We should start uploading the tck-dist and spec artifacts to maven such as we do for EE 11.
=> Ensure tck-distribution is generated in 3.0 service stream

.github/workflows/ci.yml
This is the latest service release branch.  Ensure the CI build is run whenever a pull or merge is created.
=> Ensure pulls and merges to RELEASE-3.1.1 run CI build

.github/workflows/ci.yml, api/pom.xml, pom.xml, specification/pom.xml, tck-dist/pom.xml, tck-dist/src/main/starter/pom.xml, tck/pom.xml
- Centralize dependency management to parent pom
- Update to use Arquillian boms
- Update tck starter dependencies
- Start verifying starter pom dependencies as part of CI build.
=> Standardize dependency management

.github/workflows/ci.yml, tck-dist/src/main/starter/pom.xml
Starter pom in the main branch represents the next release of concurrency.
Our verification step during ci builds will force the use of the latest version available in maven central.
=> Ensure the ci-verify step passes between releases

tck-dist/src/main/starter/pom.xml, tck/pom.xml
junit-platform-launcher is no longer a transitive dependency of junit-jupiter and will cause Arquillian to fail to discover tests at runtime when missing.
=> fix: add junit-platform-launcher

api/src/main/java/jakarta/enterprise/concurrent/ContextService.java
Another case of reading through some of our Javadoc to answer a question where I noticed a minor typo.  In this case, missing space to separate `execute` from "is",
https://jakarta.ee/specifications/platform/10/apidocs/jakarta/enterprise/concurrent/contextservice#currentContextExecutor()
=> Correction to whitespace typo in currentContextExecutor

api/src/main/java/jakarta/enterprise/concurrent/CronTrigger.java
The `dayOfWeek` description starts out `SUN-SAT, Sunday-Saturday, 0-7, *. 0 and 7 ...` which makes it difficult to understand where the list of values ends and a next sentence begins.
This PR adds a new line and two words at the start of the next sentence to clarify the distinction between the allowed values and the next sentence.
=> Add newline to improve clarity between dayOfWeek valid values and next sentence.

.github/dependabot.yml
Fixes #704
Asciidoctor does not yet support jruby 10.  See error: 
```
Error:  Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:3.2.0:process-asciidoc (asciidoc-to-pdf) on project jakarta.data-tck-dist: Execution asciidoc-to-pdf of goal org.asciidoctor:asciidoctor-maven-plugin:3.2.0:process-asciidoc failed: (ArgumentError) wrong number of arguments (given 3, expected 1..2): (LoadError) no such file to load -- asciidoctor-pdf -> [Help 1]
```
=> Ignore: jruby 10.0.0.0

.github/workflows/ci.yml, .github/workflows/update.yml
My original PR passed using the Java 25-ea build of temurin here: 
https://github.com/jakartaee/concurrency/actions/runs/14888404740/job/41814091033?pr=703
Which correctly downloaded the JDK from the location: 
https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25%2B20-ea-beta/OpenJDK-jdk_x64_linux_hotspot_25_20-ea.tar.gz
After merging some subsequent builds have failed, like so: 
https://github.com/jakartaee/concurrency/actions/runs/14909963648/job/41881609557?pr=705
It looks like the setup-java step downloaded the `jmod` archive instead of the `jdk` from: 
https://github.com/adoptium/temurin25-binaries/releases/download/jdk-25%2B21-ea-beta/OpenJDK-jmods_x64_linux_hotspot_25_21-ea.tar.gz
Which cannot be used by Maven to run a build.
I guess I was too quick.  Let's …
=> fix: toolchain error java 25

api/src/main/java/jakarta/enterprise/concurrent/Asynchronous.java, api/src/main/java/jakarta/enterprise/concurrent/Schedule.java, specification/src/main/asciidoc/jakarta-concurrency.adoc
Adds JavaDoc and specification text, as well as the update to the annotation target, to enable the existing Schedule annotation to be used directly on methods, with the meaning of having the scheduled method be automatically invoked at the times on the Schedule, according to the decision that was reached in [#624.](https://github.com/jakartaee/concurrency/issues/624#issuecomment-2725043459)
This also updates the javadoc to mention how `@Asynchronous` methods from Concurrency 3.1 and earlier can also be made to start automatically because we have seen users wanting to do that and not realizing how to achieve it.
=> Allow Schedule annotation on methods for autostart
